# vim:fileencoding=utf-8:foldmethod=marker

# Include shared settings (all major settings are defined here)
# include shared-settings.conf

allow_remote_control yes
listen_on unix:~/.config/kitty/.kitty_socket

# Setting background opacity
background_opacity 0.9

# Setting background
background_image ~/.config/kitty/backgrounds/bg-blurred-darker.png
background_image_layout scaled

# Font settings
font_family      Fira Code Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 16.0
adjust_line_height 110%

include font_symbols.conf

# Cursor
cursor_blink_interval 1 ease-in-out
cursor_trail 1
cursor_trail_color red


# Window
hide_window_decorations yes

# Misc
macos_option_as_alt yes
enable_audio_bell no
repaint_delay 15
sync_to_monitor yes

# Theme
include themes/catpuccian-mocha.conf
